development: &development
  adapter: postgresql
  database: remindmail
  username: postgres
  password: <%= ENV['DBPASS'] %>
  host:     localhost
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: remindmail

production:
  <<: *development
  database: remindmail

